spring:
  application:
    name: qtos-base
  main:
    banner-mode: off
  profiles:
    active: dev

server:
  port: 9300

qtos:
  base:
    install-script-candidates: install.sh,install.py
    uninstall-script-candidates: uninstall.sh,uninstall.py
    ui: enable
