spring:
  application:
    name: qtos-platform
  main:
    banner-mode: off
  profiles:
    active: dev
  mvc:
    log-resolved-exception: false

server:
  port: 9200

qtos:
  platform:
    base-port: 9300
